In [1]:
print('h')

h


# Heading 

**this is bold** <br>
*this is italic* <br>
_this is italic_ <br>
_**this is both_**

# Table
***
1. One
2. Two

| One | Two |
|---|---|

In [3]:
%lsmagic


Available line magics:
%alias  %alias_magic  %autoawait  %autocall  %automagic  %autosave  %bookmark  %cd  %clear  %cls  %colors  %conda  %config  %connect_info  %copy  %ddir  %debug  %dhist  %dirs  %doctest_mode  %echo  %ed  %edit  %env  %gui  %hist  %history  %killbgscripts  %ldir  %less  %load  %load_ext  %loadpy  %logoff  %logon  %logstart  %logstate  %logstop  %ls  %lsmagic  %macro  %magic  %matplotlib  %mkdir  %more  %notebook  %page  %pastebin  %pdb  %pdef  %pdoc  %pfile  %pinfo  %pinfo2  %pip  %popd  %pprint  %precision  %prun  %psearch  %psource  %pushd  %pwd  %pycat  %pylab  %qtconsole  %quickref  %recall  %rehashx  %reload_ext  %ren  %rep  %rerun  %reset  %reset_selective  %rmdir  %run  %save  %sc  %set_env  %store  %sx  %system  %tb  %time  %timeit  %unalias  %unload_ext  %who  %who_ls  %whos  %xdel  %xmode

Available cell magics:
%%!  %%HTML  %%SVG  %%bash  %%capture  %%cmd  %%debug  %%file  %%html  %%javascript  %%js  %%latex  %%markdown  %%perl  %%prun  %%pypy  %%python 

In [8]:
%%timeit
for i in range(100000000):
    pass

1.82 s ± 16.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [9]:
hello

NameError: name 'hello' is not defined

In [13]:
%%timeit
import numpy as np


101 ns ± 2.54 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [14]:
%%timeit
a = np.arange(10000)

NameError: name 'np' is not defined

In [15]:
import numpy as np

In [22]:
s = np.arange(1, 1000, 2)

In [21]:
np.random.randint(1, 100)

39

In [23]:
np.random.choice(s)

629

In [24]:
np.array([1, 2, 3])

array([1, 2, 3])

In [30]:
np.array([[[1, 2, 3], [4, 5, 6], [7, 8 , 9]], [1, 1 , 1]])

array([[list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9])],
       [1, 1, 1]], dtype=object)

In [32]:
np.zeros(1)

array([0.])

In [37]:
a = np.ones((2,2))

In [35]:
np.zeros((2, 3) * 5)

array([[[[[[[[[[0., 0., 0.],
               [0., 0., 0.]],

              [[0., 0., 0.],
               [0., 0., 0.]],

              [[0., 0., 0.],
               [0., 0., 0.]]],


             [[[0., 0., 0.],
               [0., 0., 0.]],

              [[0., 0., 0.],
               [0., 0., 0.]],

              [[0., 0., 0.],
               [0., 0., 0.]]]],



            [[[[0., 0., 0.],
               [0., 0., 0.]],

              [[0., 0., 0.],
               [0., 0., 0.]],

              [[0., 0., 0.],
               [0., 0., 0.]]],


             [[[0., 0., 0.],
               [0., 0., 0.]],

              [[0., 0., 0.],
               [0., 0., 0.]],

              [[0., 0., 0.],
               [0., 0., 0.]]]],



            [[[[0., 0., 0.],
               [0., 0., 0.]],

              [[0., 0., 0.],
               [0., 0., 0.]],

              [[0., 0., 0.],
               [0., 0., 0.]]],


             [[[0., 0., 0.],
               [0., 0., 0.]],

              [[0., 0., 0.

In [40]:
a * 5

array([[5., 5.],
       [5., 5.]])

In [43]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [47]:
np.add_docstring('1', '2')

RuntimeError: object already has a docstring

In [50]:
np.Infinity

inf

In [51]:
a.argmin()

0

In [52]:
a

array([[1., 1.],
       [1., 1.]])

In [53]:
a = np.arange(10)

In [54]:
a.argmin()

0

In [55]:
a.argmax()

9

In [56]:
a.max()

9

In [57]:
a.iloc(1)

AttributeError: 'numpy.ndarray' object has no attribute 'iloc'

# Hello World