In [1]:
import numpy as np

In [2]:
arr = np.array([0])

In [3]:
np.sin(np.deg2rad(arr))

array([0.])

In [4]:
arr = np.array([0, 45, 90, 180, 270, 360])

In [5]:
np.sin(np.deg2rad(arr))

array([ 0.00000000e+00,  7.07106781e-01,  1.00000000e+00,  1.22464680e-16,
       -1.00000000e+00, -2.44929360e-16])

In [6]:
np.sin(arr)

array([ 0.        ,  0.85090352,  0.89399666, -0.80115264, -0.17604595,
        0.95891572])

In [7]:
np.cos(np.deg2rad(arr))

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -1.00000000e+00,
       -1.83697020e-16,  1.00000000e+00])

In [9]:
np.arccos(0.5)

1.0471975511965979

In [10]:
np.array(['a', 0.50, 4]).dtype

dtype('<U3')

In [11]:
np.array(['a']).dtype

dtype('<U1')

In [12]:
np.array([0.5, 4]).dtype

dtype('float64')

In [16]:
np.array([40000, 45000]).dtype

dtype('int32')

In [17]:
arr = np.array(list(np.arange(10, 100, 10)))

In [18]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [19]:
arr.mean()

50.0

In [20]:
arr.std()

25.81988897471611

In [22]:
np.median(arr)

50.0

In [23]:
np.exp(arr)

array([2.20264658e+04, 4.85165195e+08, 1.06864746e+13, 2.35385267e+17,
       5.18470553e+21, 1.14200739e+26, 2.51543867e+30, 5.54062238e+34,
       1.22040329e+39])

In [24]:
np.log(arr)

array([2.30258509, 2.99573227, 3.40119738, 3.68887945, 3.91202301,
       4.09434456, 4.24849524, 4.38202663, 4.49980967])

In [25]:
np.log10(arr)

array([1.        , 1.30103   , 1.47712125, 1.60205999, 1.69897   ,
       1.77815125, 1.84509804, 1.90308999, 1.95424251])

# Aggregate Function

In [26]:
heights = np.array([150, 189, 165, 160])

In [27]:
heights

array([150, 189, 165, 160])

In [28]:
heights.mean()

166.0

In [29]:
np.median(heights)

162.5

In [30]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [31]:
len(arr)

9

In [32]:
arr[1]

20

In [33]:
arr[[0]]

array([10])

In [35]:
arr[[0, 1]:8]

TypeError: slice indices must be integers or None or have an __index__ method

In [36]:
arr[-1]

90

In [37]:
arr[::2]

array([10, 30, 50, 70, 90])

In [38]:
arr[::3]

array([10, 40, 70])

In [39]:
arr[::-1]

array([90, 80, 70, 60, 50, 40, 30, 20, 10])

In [40]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
arr2d = [[i, j, k] for i in range(0, 100, 10) for j in range(110, 200, 10) for k in range(200, 300, 10)]

In [43]:
arr2d

[[0, 110, 200],
 [0, 110, 210],
 [0, 110, 220],
 [0, 110, 230],
 [0, 110, 240],
 [0, 110, 250],
 [0, 110, 260],
 [0, 110, 270],
 [0, 110, 280],
 [0, 110, 290],
 [0, 120, 200],
 [0, 120, 210],
 [0, 120, 220],
 [0, 120, 230],
 [0, 120, 240],
 [0, 120, 250],
 [0, 120, 260],
 [0, 120, 270],
 [0, 120, 280],
 [0, 120, 290],
 [0, 130, 200],
 [0, 130, 210],
 [0, 130, 220],
 [0, 130, 230],
 [0, 130, 240],
 [0, 130, 250],
 [0, 130, 260],
 [0, 130, 270],
 [0, 130, 280],
 [0, 130, 290],
 [0, 140, 200],
 [0, 140, 210],
 [0, 140, 220],
 [0, 140, 230],
 [0, 140, 240],
 [0, 140, 250],
 [0, 140, 260],
 [0, 140, 270],
 [0, 140, 280],
 [0, 140, 290],
 [0, 150, 200],
 [0, 150, 210],
 [0, 150, 220],
 [0, 150, 230],
 [0, 150, 240],
 [0, 150, 250],
 [0, 150, 260],
 [0, 150, 270],
 [0, 150, 280],
 [0, 150, 290],
 [0, 160, 200],
 [0, 160, 210],
 [0, 160, 220],
 [0, 160, 230],
 [0, 160, 240],
 [0, 160, 250],
 [0, 160, 260],
 [0, 160, 270],
 [0, 160, 280],
 [0, 160, 290],
 [0, 170, 200],
 [0, 170, 210],
 [0, 170

In [44]:
arr2d = [[10, 20, 30], [40, 50, 60], [70, 80, 90]]

In [49]:
arr2d = np.array(arr2d)
arr2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [51]:
arr2d.ndim

2

In [53]:
arr2d[[1,2], [,]]

SyntaxError: invalid syntax (<ipython-input-53-a6f9269d48be>, line 1)