In [1]:
import numpy as np

In [2]:
my_list = [1, 2, 3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

# Print Even Numbers using NP

In [7]:
num = 20
np.arange(0, num + 1, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [8]:
num = 20
np.arange(0, num + 1, 3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [9]:
np.zeros(3)

array([0., 0., 0.])

In [10]:
np.zeros([3,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros((3, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones([3, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.linspace(0, 5, 100)

array([0.        , 0.05050505, 0.1010101 , 0.15151515, 0.2020202 ,
       0.25252525, 0.3030303 , 0.35353535, 0.4040404 , 0.45454545,
       0.50505051, 0.55555556, 0.60606061, 0.65656566, 0.70707071,
       0.75757576, 0.80808081, 0.85858586, 0.90909091, 0.95959596,
       1.01010101, 1.06060606, 1.11111111, 1.16161616, 1.21212121,
       1.26262626, 1.31313131, 1.36363636, 1.41414141, 1.46464646,
       1.51515152, 1.56565657, 1.61616162, 1.66666667, 1.71717172,
       1.76767677, 1.81818182, 1.86868687, 1.91919192, 1.96969697,
       2.02020202, 2.07070707, 2.12121212, 2.17171717, 2.22222222,
       2.27272727, 2.32323232, 2.37373737, 2.42424242, 2.47474747,
       2.52525253, 2.57575758, 2.62626263, 2.67676768, 2.72727273,
       2.77777778, 2.82828283, 2.87878788, 2.92929293, 2.97979798,
       3.03030303, 3.08080808, 3.13131313, 3.18181818, 3.23232323,
       3.28282828, 3.33333333, 3.38383838, 3.43434343, 3.48484848,
       3.53535354, 3.58585859, 3.63636364, 3.68686869, 3.73737

In [16]:
np.ones([4,5,6])

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [17]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [19]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
np.random.randint(10)

8

In [21]:
np.random.random(20)

array([0.62810595, 0.66484867, 0.08365245, 0.06968237, 0.0492854 ,
       0.19908925, 0.21888758, 0.70129736, 0.12442786, 0.51974582,
       0.36479417, 0.96007908, 0.77633305, 0.87911825, 0.128482  ,
       0.40446699, 0.26638285, 0.57264095, 0.68616611, 0.35027277])

In [22]:
np.random.rand(10)

array([0.65026359, 0.38096119, 0.45467942, 0.26868114, 0.86431022,
       0.02140176, 0.08193397, 0.69508627, 0.12857776, 0.70096899])

In [23]:
np.random.rand(1)

array([0.76860133])

In [24]:
np.random.randn(2)

array([-0.68277403,  0.24700428])

In [25]:
np.random.randn(2,2)

array([[ 1.02285577,  1.62304079],
       [-0.05304899, -0.7097523 ]])

In [26]:
np.random.randint(0, 100)

2

In [27]:
np.random.randint(0, 100, 10)

array([90, 97, 65, 44,  6, 58,  5, 87,  9, 12])

In [28]:
np.random.randint(0 , 101, 10)

array([20, 65, 14, 36, 86, 19, 90, 47, 41, 82])

In [30]:
arr = np.arange(0, 169)

In [31]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168])

In [32]:
arr.reshape(13, 13)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38],
       [ 39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51],
       [ 52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64],
       [ 65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77],
       [ 78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103],
       [104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116],
       [117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142],
       [143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168]])

In [33]:
arr.reshape(13, 12)

ValueError: cannot reshape array of size 169 into shape (13,12)

In [34]:
randarr = np.random.randint(0, 169, 10)

In [35]:
randarr

array([109,  31,  52, 103, 132,  71, 166, 161,  47,  29])

In [36]:
randarr.max()

166

In [37]:
arr.max()

168

In [43]:
print(arr.sort())

None


In [39]:
randarr.sort()

In [40]:
print(randarr.sort())

None


In [41]:
sorted(randarr)

[29, 31, 47, 52, 71, 103, 109, 132, 161, 166]

In [42]:
randarr

array([ 29,  31,  47,  52,  71, 103, 109, 132, 161, 166])

In [44]:
randarr.argmax()

9

In [45]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168])

In [48]:
rand = np.random.randint(0 , 100, 10)

In [49]:
rand

array([75, 60, 30, 99, 66, 21,  9, 47, 46, 94])

In [50]:
sorted(rand)

[9, 21, 30, 46, 47, 60, 66, 75, 94, 99]

In [51]:
rand.argmax()

3

In [52]:
rand

array([75, 60, 30, 99, 66, 21,  9, 47, 46, 94])

In [53]:
rand = sorted(rand)

In [54]:
rand

[9, 21, 30, 46, 47, 60, 66, 75, 94, 99]

In [55]:
rand.argmax()

AttributeError: 'list' object has no attribute 'argmax'

In [56]:
arr.shape()

TypeError: 'tuple' object is not callable

In [59]:
arr = np.arange(0, 169)

In [60]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168])

In [62]:
arr.shape

(169,)

In [63]:
arr.reshape(13, 13)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12],
       [ 13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25],
       [ 26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38],
       [ 39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51],
       [ 52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64],
       [ 65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77],
       [ 78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103],
       [104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116],
       [117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
       [130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142],
       [143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155],
       [156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168]])

In [64]:
arr.shape

(169,)

In [65]:
arr.dtype

dtype('int32')

In [67]:
st = np.array(['hello'])

In [68]:
st.dtype

dtype('<U5')